openapi: 3.0.0
info:
  title: New10 Loan API
  description:

servers:
  - url: http://localhost:3000/dev
    description: Local development server

paths:
  /create/{amount}:
    get:
      summary:
      description:
      parameters:
        - name: amount
          in: path
          required: true
          description: Loan amount
          schema:
            type: number
            format: float
            minimum: 1
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  amount:
                    type: number
                    format: float
                  status:
                    type: string
                    enum:
                      - offered
                      - disbursed
                  id:
                    type: string
                  createdAt:
                    type: string
                    format: date-time
                required:
                  - amount
                  - status
                  - id
                  - createdAt
        "500":
          description: Bad request / Internal Error
  /delete/{id}:
    get:
  /all:
    get:
  /disburse/{id}:
    get:
